name: Validate packages

on:
  push:
    branches-ignore:
      - main

defaults:
  run:
    shell: bash

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Packages
        run: npm run precommit
