name: Verify major and minor versions

on: push

defaults:
  run:
    shell: bash

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check versions
        run: .github/tools/version-check.sh
